/**
 * GET /api/suggest — preset questions for the home page, generated by the fast
 * model from the LIVE table catalog (no hardcoded examples: suggestions reflect
 * what is actually in ClickHouse).
 *
 * Response 200: strictly suggestResponseSchema { questions } — an empty array
 * is valid and means "no presets" (LLM/ClickHouse unavailable); the UI simply
 * skips rendering chips in that case. In-process memory cache for SUGGEST_TTL_MS —
 * presets need not be fresher than the catalog.
 */
import { NextResponse } from "next/server";
import { suggestResponseSchema } from "@/lib/contracts";
import { createReadonlyClient } from "@/lib/clickhouse";
import { getCatalog } from "@/lib/agent/explore";
import { suggestQuestions } from "@/lib/agent/triage";

// Node.js runtime: ClickHouse client and OpenRouter call out with creds from env.
export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const SUGGEST_TTL_MS = 10 * 60_000;

let cache: { questions: string[]; at: number } | undefined;

export async function GET() {
  if (cache && Date.now() - cache.at < SUGGEST_TTL_MS) {
    return NextResponse.json(suggestResponseSchema.parse({ questions: cache.questions }));
  }
  const ro = createReadonlyClient();
  try {
    const catalog = await getCatalog(ro);
    const questions = await suggestQuestions(catalog);
    cache = { questions, at: Date.now() };
    return NextResponse.json(suggestResponseSchema.parse({ questions }));
  } catch (err) {
    // Presets are non-critical: any failure → valid empty response, not 5xx.
    console.warn(
      `/api/suggest: falling back to empty presets — ${err instanceof Error ? err.message : String(err)}`,
    );
    return NextResponse.json(suggestResponseSchema.parse({ questions: [] }));
  } finally {
    await ro.close();
  }
}
