/**
 * GET /api/suggest — preset questions for the home page, generated by the fast
 * model from the LIVE table catalog (no hardcoded examples: suggestions reflect
 * what is actually in ClickHouse).
 *
 * The UI locale (cookie NEXT_LOCALE / Accept-Language) sets the preset
 * language — the suggestQuestions prompt asks for questions in the interface
 * language.
 *
 * Response 200: strictly suggestResponseSchema { questions } — an empty array
 * is valid and means "no presets" (LLM/ClickHouse unavailable); the UI simply
 * skips rendering chips in that case. In-process memory cache PER LOCALE for
 * SUGGEST_TTL_MS — presets need not be fresher than the catalog.
 */
import { NextResponse } from "next/server";
import { cookies, headers } from "next/headers";
import { suggestResponseSchema } from "@/lib/contracts";
import { createReadonlyClient } from "@/lib/clickhouse";
import { getCatalog } from "@/lib/agent/explore";
import { suggestQuestions } from "@/lib/agent/triage";
import {
  LOCALE_COOKIE,
  LOCALE_ENGLISH_NAME,
  negotiateLocale,
  type Locale,
} from "@/lib/i18n/locale";

// Node.js runtime: ClickHouse client and OpenRouter call out with creds from env.
export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const SUGGEST_TTL_MS = 10 * 60_000;

const cache = new Map<Locale, { questions: string[]; at: number }>();

export async function GET() {
  const [cookieStore, headerStore] = await Promise.all([cookies(), headers()]);
  const locale = negotiateLocale(
    cookieStore.get(LOCALE_COOKIE)?.value,
    headerStore.get("accept-language"),
  );

  const cached = cache.get(locale);
  if (cached && Date.now() - cached.at < SUGGEST_TTL_MS) {
    return NextResponse.json(suggestResponseSchema.parse({ questions: cached.questions }));
  }
  const ro = createReadonlyClient();
  try {
    const catalog = await getCatalog(ro);
    const questions = await suggestQuestions(catalog, LOCALE_ENGLISH_NAME[locale]);
    cache.set(locale, { questions, at: Date.now() });
    return NextResponse.json(suggestResponseSchema.parse({ questions }));
  } catch (err) {
    // Presets are non-critical: any failure → valid empty response, not 5xx.
    console.warn(
      `/api/suggest: falling back to empty presets — ${err instanceof Error ? err.message : String(err)}`,
    );
    return NextResponse.json(suggestResponseSchema.parse({ questions: [] }));
  } finally {
    await ro.close();
  }
}
